///////////////////////////////////////////////////////////
//  Coupon.cs
//  Implementation of the Class Coupon
//  Generated by Enterprise Architect
//  Created on:      04-Dec-2023 4:24:24 PM
//  Original author: User
///////////////////////////////////////////////////////////

using OOSEStore.Models;
using OOSEStore.Strategies;
namespace OOSEStore.Decorators
{
    public abstract class CouponDecorator : PricingStrategy
    {

        public PricingStrategy m_PricingStrategy;
        public bool IsItemDiscount { get; internal set; }
        public CouponDecorator(PricingStrategy basePriceStrategy)
        {
            m_PricingStrategy = basePriceStrategy;
            IsItemDiscount = true;
        }
        /// <summary>
        /// Discounts do not add to Loyalty points they might reduce infact...
        /// </summary>
        /// 
        /// <param name="customer"></param>
        protected override int AddLoyalty(Transaction transaction, Customer customer, SaleItem item)
        {
            return 0;
        }

        /// <summary>
        /// 
        /// </summary>
        /// 
        /// <param name="transaction"></param>
        /// <param name="customer"></param>
        /// <param name="item"></param>
        protected abstract decimal CalculateDiscount(Transaction transaction, Customer customer, SaleItem item, decimal unitPrice);


        protected override decimal InternalCalculate(Transaction transaction, Customer customer, SaleItem item)
        {
            var discount = 0m;
            if (IsItemDiscount)
            {
                var baseItemPrice = m_PricingStrategy.CalculatePrice(transaction, customer, item);
                discount = CalculateDiscount(transaction, customer, item, baseItemPrice);

                Console.Write($" \tDiscount is {discount}");
                return baseItemPrice - discount;
            }
            discount = CalculateDiscount(transaction, customer, item, 0);
            return discount;
        }

    }//end Coupon

}//end namespace Store