///////////////////////////////////////////////////////////
//  LoyaltyDiscount.cs
//  Implementation of the Class LoyaltyDiscount
//  Generated by Enterprise Architect
//  Created on:      04-Dec-2023 4:24:25 PM
//  Original author: User
///////////////////////////////////////////////////////////

using System.Xml;

using OOSEStore.Models;
using OOSEStore.Strategies;
namespace OOSEStore.Decorators
{
    public class LoyaltyDiscountDecorator : CouponDecorator
    {
        protected const int MINLOYALTYPOINTS = 5;
        protected Product m_FreeProduct;
        private bool m_discountApplied;
        private SaleItem m_saleItem;

        public LoyaltyDiscountDecorator(PricingStrategy basePriceStrategy) : base(basePriceStrategy)
        {
            m_BaseValue = MINLOYALTYPOINTS;
            m_FreeProduct = new Product(ProductTypes.MusicCD);
            IsItemDiscount = false;

        }


        /// <summary>
        /// 
        /// </summary>
        /// 
        /// <param name="transaction"></param>
        /// <param name="customer"></param>
        /// <param name="item"></param>
        protected override decimal CalculateDiscount(Transaction transaction, Customer customer, SaleItem item, decimal unitPrice)
        {
            if (customer.LoyaltyPoints > (int)m_BaseValue)
            {
                m_discountApplied = true;
                customer.LoyaltyPoints -= (int)m_BaseValue;
                m_saleItem = new SaleItem(m_FreeProduct, 1, SaleTypes.Free);

                transaction.AddProduct(m_saleItem, customer);
            }
            return 0;
        }
        public override void ToXml(XmlElement source)
        {
            if (!m_discountApplied) return;
            XmlElement element = source.OwnerDocument.CreateElement("LoyaltyDiscount");
            element.SetAttribute("LoyaltyUsed", (-1 * m_BaseValue).ToString());
            element.SetAttribute("_", $"Free {m_saleItem.GetProductType()} added to purchases.");
            source.AppendChild(element);
        }


    }//end LoyaltyDiscount

}//end namespace Store