///////////////////////////////////////////////////////////
//  RentalPricingFactory.cs
//  Implementation of the Class RentalPricingFactory
//  Generated by Enterprise Architect
//  Created on:      04-Dec-2023 4:24:26 PM
//  Original author: User
///////////////////////////////////////////////////////////

using OOSEStore.Models;
using OOSEStore.Strategies;

namespace OOSEStore.Factories
{
    public class RentalPricingFactory : PricingFactory
    {
        public override PricingStrategy GetPricingStrategy(SaleItem item)
        {
            switch (item.GetProductType())
            {
                case ProductTypes.MusicCD: return new MusicCDRentalPriceStrategy();
                case ProductTypes.Movie: return new MovieRentalPriceStrategy();
                case ProductTypes.Book: return new BookRentalPriceStrategy();
                case ProductTypes.Ps4: return new Ps4RentalPriceStrategy();
                case ProductTypes.XBox: return new XBoxRentalPriceStrategy();
                case ProductTypes.FreeItem: return new FreePriceStrategy();
                case ProductTypes.VideoGame: return new VideoGameRentalPriceStrategy();
            }
            return new TransactionPricingStrategy();
        }

    }//end RentalPricingFactory

}//end namespace Store