///////////////////////////////////////////////////////////
//  SalePricingFactory.cs
//  Implementation of the Class SalePricingFactory
//  Generated by Enterprise Architect
//  Created on:      04-Dec-2023 4:24:26 PM
//  Original author: User
///////////////////////////////////////////////////////////

using OOSEStore.Models;
using OOSEStore.Strategies;

namespace OOSEStore.Factories
{
    public class SalePricingFactory : PricingFactory
    {
        public override PricingStrategy GetPricingStrategy(SaleItem item)
        {
            switch (item.GetProductType())
            {
                case ProductTypes.MusicCD: return new MusicCDSalePricingStrategy();
                case ProductTypes.Movie: return new MovieRentalFactory().GetMovieRentalStrategy(item.GetProductSubType());
                case ProductTypes.Book: return new BookSalePricingStrategy();
                case ProductTypes.Ps4: return new Ps4SalePricingStrategy();
                case ProductTypes.XBox: return new XBoxSalePricingStrategy();
                case ProductTypes.FreeItem: return new FreePriceStrategy();
                case ProductTypes.VideoGame: return new VideoGameSalePricingStrategy();
            }
            return new TransactionPricingStrategy();
        }

    }//end SalePricingFactory

}//end namespace Store