///////////////////////////////////////////////////////////
//  SaleItem.cs
//  Implementation of the Class SaleItem
//  Generated by Enterprise Architect
//  Created on:      04-Dec-2023 4:24:26 PM
//  Original author: User
///////////////////////////////////////////////////////////

namespace OOSEStore.Models
{


    public class NullSaleItem : SaleItem
    {
        static SaleItem? m_item;
        private NullSaleItem(Product? product, int qty, SaleTypes saleType) : base(product, qty, saleType) { }
        public static SaleItem Instance
        {
            get
            {
                if (m_item == null) m_item = new NullSaleItem(null, 0, SaleTypes.Free);
                return m_item;
            }
        }

    }

}//end namespace Store