///////////////////////////////////////////////////////////
//  Product.cs
//  Implementation of the Class Product
//  Generated by Enterprise Architect
//  Created on:      04-Dec-2023 4:24:25 PM
//  Original author: User
///////////////////////////////////////////////////////////

using System.Xml;

namespace OOSEStore.Models
{
    public class Product
    {

        public bool IsPriceFree = false;
        public ProductTypes m_ProductTypes;
        public ProductSubTypes m_ProductSubTypes;

        public Product(ProductTypes productType) : this(productType, ProductSubTypes.None) { }
        public Product(ProductTypes productType, ProductSubTypes subType)
        {
            m_ProductTypes = productType;
            m_ProductSubTypes = subType;
        }

        public void ToXml(XmlElement source)
        {
            source.SetAttribute("ProductType", m_ProductTypes.ToString());
            source.SetAttribute("ProductSubType", m_ProductSubTypes.ToString());
        }


    }//end Product

}//end namespace Store