///////////////////////////////////////////////////////////
//  ProdutTypes.cs
//  Implementation of the Class ProdutTypes
//  Generated by Enterprise Architect
//  Created on:      04-Dec-2023 4:24:25 PM
//  Original author: User
///////////////////////////////////////////////////////////

namespace OOSEStore.Models
{
    public enum ProductTypes : int
    {
        FreeItem,
        Movie,
        VideoGame,
        MusicCD,
        XBox,
        Ps4,
        Book

    }//end ProdutTypes

}//end namespace Store