///////////////////////////////////////////////////////////
//  SaleTypes.cs
//  Implementation of the Class SaleTypes
//  Generated by Enterprise Architect
//  Created on:      04-Dec-2023 4:24:26 PM
//  Original author: User
///////////////////////////////////////////////////////////

namespace OOSEStore.Models
{
    public enum SaleTypes : int
    {

        Rental,
        Sale,
        Free
    }//end SaleTypes

}//end namespace Store