///////////////////////////////////////////////////////////
//  BookRentalPriceStrategy.cs
//  Implementation of the Class BookRentalPriceStrategy
//  Generated by Enterprise Architect
//  Created on:      04-Dec-2023 4:24:24 PM
//  Original author: User
///////////////////////////////////////////////////////////

using OOSEStore.Models;

namespace OOSEStore.Strategies
{
    public class BookRentalPriceStrategy : RentalPricingStrategy
    {

        public BookRentalPriceStrategy()
        {
            m_BaseValue = 1m;
            m_ProductType = ProductTypes.Book;
            m_SaleType = SaleTypes.Rental;
        }

    }//end BookRentalPriceStrategy

}//end namespace Store