///////////////////////////////////////////////////////////
//  BookSalePricingStrategy.cs
//  Implementation of the Class BookSalePricingStrategy
//  Generated by Enterprise Architect
//  Created on:      04-Dec-2023 4:24:24 PM
//  Original author: User
///////////////////////////////////////////////////////////

using OOSEStore.Models;

namespace OOSEStore.Strategies
{
    public class BookSalePricingStrategy : SalePricingStrategy
    {

        public BookSalePricingStrategy()
        {
            Value = 2m;
            m_ProductType = ProductTypes.Book;
            m_SaleType = SaleTypes.Sale;

        }

    }//end BookSalePricingStrategy

}//end namespace Store