///////////////////////////////////////////////////////////
//  MovieRentalPriceStrategy.cs
//  Implementation of the Class MovieRentalPriceStrategy
//  Generated by Enterprise Architect
//  Created on:      04-Dec-2023 4:24:25 PM
//  Original author: User
///////////////////////////////////////////////////////////

using OOSEStore.Models;

namespace OOSEStore.Strategies
{
    public class ChildrenMovieRentalPriceStrategy : MovieRentalPriceStrategy
    {

        public ChildrenMovieRentalPriceStrategy()
        {
            m_FreeRentalDays = 3;
            m_MinCost = 1.5m;
            m_BaseValue = 1.5m;
            m_ProductType = ProductTypes.Movie;
            m_SaleType = SaleTypes.Rental;
        }

    }//end ChildrenMovieRentalPriceStrategy

}//end namespace Store