///////////////////////////////////////////////////////////
//  MovieSalePricingStrategy.cs
//  Implementation of the Class MovieSalePricingStrategy
//  Generated by Enterprise Architect
//  Created on:      04-Dec-2023 4:24:25 PM
//  Original author: User
///////////////////////////////////////////////////////////

using OOSEStore.Models;

namespace OOSEStore.Strategies
{
    public class MovieSalePricingStrategy : SalePricingStrategy
    {

        public MovieSalePricingStrategy()
        {
            Value = 4m;
            m_ProductType = ProductTypes.Movie;
            m_SaleType = SaleTypes.Sale;

        }

        /// <summary>
        /// 
        /// </summary>
        /// 
        /// <param name="customer"></param>
        protected override int AddLoyalty(Customer customer)
        {

            return 0;
        }

        /// <summary>
        /// 
        /// </summary>
        /// 
        /// <param name="transaction"></param>
        /// <param name="customer"></param>
        /// <param name="item"></param>
        public override decimal CalculatePrice(Transaction transaction, Customer customer, SaleItem item)
        {

            return 0;
        }

        /// <summary>
        /// 
        /// </summary>
        /// 
        /// <param name="transaction"></param>
        /// <param name="customer"></param>
        /// <param name="item"></param>
        protected override decimal InternalCalculate(Transaction transaction, Customer customer, SaleItem item)
        {

            return 0;
        }

    }//end MovieSalePricingStrategy

}//end namespace Store