///////////////////////////////////////////////////////////
//  MusicCDRentalPriceStrategy.cs
//  Implementation of the Class MusicCDRentalPriceStrategy
//  Generated by Enterprise Architect
//  Created on:      04-Dec-2023 4:24:25 PM
//  Original author: User
///////////////////////////////////////////////////////////

using OOSEStore.Models;

namespace OOSEStore.Strategies
{
    public class MusicCDRentalPriceStrategy : RentalPricingStrategy
    {
        public MusicCDRentalPriceStrategy()
        {
            Value = 1m;
            m_ProductType = ProductTypes.MusicCD;
            m_SaleType = SaleTypes.Rental;

            LoyaltyPoints = 1;
        }
    }//end MusicCDRentalPriceStrategy

}//end namespace Store