///////////////////////////////////////////////////////////
//  MusicCDSalePricingStrategy.cs
//  Implementation of the Class MusicCDSalePricingStrategy
//  Generated by Enterprise Architect
//  Created on:      04-Dec-2023 4:24:25 PM
//  Original author: User
///////////////////////////////////////////////////////////

using OOSEStore.Models;

namespace OOSEStore.Strategies
{
    public class MusicCDSalePricingStrategy : SalePricingStrategy
    {
        public MusicCDSalePricingStrategy()
        {
            m_BaseValue = 1m;
            m_ProductType = ProductTypes.MusicCD;
            m_SaleType = SaleTypes.Sale;

            LoyaltyPoints = 1;
        }

    }//end MusicCDSalePricingStrategy

}//end namespace Store