///////////////////////////////////////////////////////////
//  Ps4RentalPriceStrategy.cs
//  Implementation of the Class Ps4RentalPriceStrategy
//  Generated by Enterprise Architect
//  Created on:      04-Dec-2023 4:24:25 PM
//  Original author: User
///////////////////////////////////////////////////////////

using OOSEStore.Models;

namespace OOSEStore.Strategies
{
    public class Ps4RentalPriceStrategy : RentalPricingStrategy
    {

        public Ps4RentalPriceStrategy()
        {
            Value = 4m;
            m_ProductType = ProductTypes.Ps4;
            m_SaleType = SaleTypes.Rental;

            LoyaltyPoints = 2;

        }

    }//end Ps4RentalPriceStrategy

}//end namespace Store