///////////////////////////////////////////////////////////
//  Ps4SalePricingStrategy.cs
//  Implementation of the Class Ps4SalePricingStrategy
//  Generated by Enterprise Architect
//  Created on:      04-Dec-2023 4:24:25 PM
//  Original author: User
///////////////////////////////////////////////////////////

using OOSEStore.Models;

namespace OOSEStore.Strategies
{
    public class Ps4SalePricingStrategy : SalePricingStrategy
    {

        public Ps4SalePricingStrategy()
        {
            m_BaseValue = 40m;
            m_ProductType = ProductTypes.Ps4;
            m_SaleType = SaleTypes.Sale;

            LoyaltyPoints = 2;

        }

    }//end Ps4SalePricingStrategy

}//end namespace Store