///////////////////////////////////////////////////////////
//  XBoxSalePricingStrategy.cs
//  Implementation of the Class XBoxSalePricingStrategy
//  Generated by Enterprise Architect
//  Created on:      04-Dec-2023 4:24:26 PM
//  Original author: User
///////////////////////////////////////////////////////////

using OOSEStore.Models;

namespace OOSEStore.Strategies
{
    public class VideoGameSalePricingStrategy : SalePricingStrategy
    {

        public VideoGameSalePricingStrategy()
        {
            Value = 45m;
            m_ProductType = ProductTypes.VideoGame;
            m_SaleType = SaleTypes.Sale;

            LoyaltyPoints = 2;

        }

    }//end VideoGameSalePricingStrategy

}//end namespace Store